### ISSUE TITLE
BaseActivity中的@Nullable注解问题

### ISSUE THREAD

**Issue by HXQWill** [ImmortalZ/TransitionHelper#12]
public abstract class BaseActivity extends AppCompatActivity {

    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {

请教一下，为什么要添加为空注解?

**Comment by ImmortalZ** [comment]
这个是AS自动生成的，只是告诉我们savedInstanceState可以为空罢了，与TransitionHelper没有关系的=.=
