### ISSUE TITLE
是版本问题还是啥的 代码中的动画不对 起始点都在0，0

### ISSUE THREAD

**Issue by jsbsdbd1025** [ImmortalZ/TransitionHelper#16]
ObjectAnimator.ofFloat(child, "translationX", 0, -bean.translationX)
这句代码是从 X = 0  ->  X = -bean.translationX  横向的平移

我是设置  ivTemp 的setX setY
然后  ObjectAnimator.ofFloat(child, "translationX", child.getX(), bean.translationX),

**Comment by ImmortalZ** [comment]
你好可以看下你完整的使用代码吗？（是怎么start的 和 是怎么 show的）我这边好还原看下

**Comment by jsbsdbd1025** [comment]
InflateShowMethod  这个类中 

 ObjectAnimator.ofFloat(child, "translationX", 0, -bean.translationX),
                ObjectAnimator.ofFloat(child, "translationY", 0, -bean.translationY),
                ObjectAnimator.ofFloat(child, "scaleX", 1,1/bean.scale),
                ObjectAnimator.ofFloat(child, "scaleY", 1,1/bean.scale)

ObjectAnimator.ofFloat方法是从 0 到 -bean.translationY的位移

**Comment by ImmortalZ** [comment]
translationX , translationY 的计算方式是 原位置 - 目标位置
`bean.translationX = bean.originRect.left + bean.originWidth / 2 - bean.targetRect.left - bean.targetWidth / 2;
 bean.translationY = bean.originRect.top + bean.originHeight / 2 - bean.targetRect.top - bean.targetHeight / 2;`
所以 ObjectAnimator.ofFloat(child, "translationX", 0, -bean.translationX),
ObjectAnimator.ofFloat(child, "translationY", 0, -bean.translationY), 这里面是负的值
为了简便使用，我是直接封装好了 原位置 移动到 目标位置 的计算和动画效果（详情可以参考InflateShowMethod，ColorShowMethod），如果想要自定义位移的动画，可以自己写一个类继承自ShowMethod这个抽象基类，然后TransitionsHeleper.build(this).setShowMethod(自定义的类)  这样的方式来实现

**Comment by ImmortalZ** [comment]
部分机型FrameLayout设置margin无效导致的，已经修正
