### ISSUE TITLE
效果不错,就是不够实用

### ISSUE THREAD

**Issue by qiangxi** [ImmortalZ/TransitionHelper#2]
提出1点不足和1点建议:
不足:不够实用,页面跳转往往需要用intent携带数据进行传递,你干脆没这个参数,你让大伙怎么用你的库?建议赶紧改进.
建议:既然涉及到了携带数据进行页面跳转,那么应该添加动画相关的监听,比如从A界面进入B界面,如果动画还没加载完就进行请求数据操作,或者数据还没加载出来,动画就已经结束了,这样展现的效果都不好,给个动画监听,比如动画开始加载,动画加载中,动画加载完毕等监听或回调,让大伙可以根据你的各个回调做相应的操作,这样数据的展现与动画的执行就有了很好的协调性.

**Comment by ImmortalZ** [comment]
嗯.intent这里我也注意到了，我现在马上改改

**Comment by ImmortalZ** [comment]
intent添加好了。
compile 'me.immortalz:transitionhelper:1.0.5'
动画监听我下个版本再添加

**Comment by ImmortalZ** [comment]
非常感谢你的建议，非常棒
