### ISSUE TITLE
动画位置不对

### ISSUE THREAD

**Issue by qq273681448** [ImmortalZ/TransitionHelper#3]
新出的动画控件位置偏高，只有在我用ColorStyle主题的时候是对应的，当我切换到其他主题，新出的动画位置不对应，请问是为什么，谢谢！！！！

**Comment by ImmortalZ** [comment]
新出的动画控件是指material design中的控件么？这样吧，我加你的QQ联系吧，你的Q是 273681448么

**Comment by qq273681448** [comment]
是的，非常感谢大神

**Comment by qq273681448** [comment]
是的，非常感谢大神

**Comment by qq273681448** [comment]
是这个QQ，我只引用了    compile 'me.immortalz:transitionhelper:1.0.5'，bt弹出新activity，button的动画位置偏上，感觉忽略了标题栏高度
