### ISSUE TITLE
缩放设置的宽高参数写反了；获取的view尺寸有误

### ISSUE THREAD

**Issue by TomeOkin** [ImmortalZ/TransitionHelper#4]
1. [缩放设置的宽高参数写反了][scale_args]   

2. 如果view部分位于屏幕外，getGlobalVisibleRect 获取的尺寸不是理想值，可以改为：
``` java
int out[] = new int[2];
view.getLocationOnScreen(out);
return new Rect(out[0], out[1], out[0] + view.getWidth(), out[1] + view.getHeight());
```

[scale_args]: https://github.com/ImmortalZ/TransitionHelper/blob/master/transitionhelper/src/main/java/immortalz/me/library/TransitionsHeleper.java#L210

**Comment by ImmortalZ** [comment]
进行了相应的修改，更正。多谢反馈
