### ISSUE TITLE
存在内存泄露

### ISSUE THREAD

**Issue by jackieliu-52** [ImmortalZ/TransitionHelper#5]
我这边从不同的Recylerview的Item进入另外一个Activity，提示有
`TransitionsHeleper.showMethod`泄露了新进入的Activity 变量名为XXXActivity instance。
吐槽一下Heleper

**Comment by anjiao** [comment]
```
    originalBitmap = Bitmap.createBitmap(bean.windowWidth, bean.windowHeight, Bitmap.Config.RGB_565);
```

这里报错说OOM 我连续打开的情况下

**Comment by zhangruiyu** [comment]
能不能把library  android:label="@string/app_name"这个去了再发一下  会和本身起冲突 不知道为什么加了
tools:replace="android:lable"都没用

**Comment by zengyimou** [comment]
originalBitmap = Bitmap.createBitmap(bean.windowWidth, bean.windowHeight, Bitmap.Config.RGB_565);
OOM了

**Comment by luddite1989** [comment]
作者也不维护了

**Comment by ImmortalZ** [comment]
最新的版本已经解决了，太久没有维护抱歉了
